const app=document.querySelector('#app'), title=document.querySelector('#pageTitle'), action=document.querySelector('#pageAction'), modal=document.querySelector('#modal'), csvInput=document.querySelector('#csvInput');
const STORE='climbtracker.pwa.v1';
const GOOGLE_CLIENT_ID='1069011973327-6dkngvo8od1aoold8msd9kvu4la4soi4.apps.googleusercontent.com';
const DRIVE_SCOPE='https://www.googleapis.com/auth/drive.file';
const DRIVE_BACKUP_NAME='Climbtracker_Backup.csv';
let googleTokenClient=null,googleRestoreTokenClient=null;
const defaults={climbs:[],logs:[],gyms:[],calorieGoal:0};
let state=load(),tab='log',logType='Boulder',statsType='Boulder',statsGrade=null;
const inclines=['Slab','Vertical','Overhang','Roof','Chimney'];
const holds=['Jug','Crimp','Sloper','Pinch','Pocket','Volume','Crack','Arete'];
const moves=['Cross','Gaston','Campus','Throw','Lockoff','Heel Hook','Toe Hook','Drop Knee','High Foot','Kneebar','Bat-Hang','Dyno','Paddle','Step-Up','Lache','Coordo','Press','Mantle','Balance','Fist Jam','Hand Jam'];
const boulder=Array.from({length:18},(_,i)=>String(i));
const sport=[];for(let n=5;n<=9;n++) sport.push(String(n));for(let n=10;n<=15;n++) for(const l of ['a','b','c','d']) sport.push(`${n}${l}`);
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(STORE,JSON.stringify(state));render()}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function uid(){return Date.now()*1000+Math.floor(Math.random()*1000)}
function dayStart(d=new Date()){return new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime()}
function ymd(ts){return new Date(ts).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function displayGrade(c){return c.type==='Boulder'?`V${c.grade}`:`5.${c.grade}`}
function gradeScore(g){const n=parseInt(String(g).match(/\d+/)?.[0]||0),last=String(g).slice(-1);return n*10+({a:1,b:2,c:3,d:4}[last]||0)}
function getHardest(arr){return arr.length?[...arr].sort((a,b)=>gradeScore(b.grade)-gradeScore(a.grade))[0]:null}
function closeModal(){modal.close();modal.innerHTML=''}
function openModal(name,body,onReady){modal.innerHTML=`<div class="modal-head"><h3>${esc(name)}</h3><button class="icon-btn" style="position:static" onclick="closeModal()">×</button></div><div class="modal-body">${body}</div>`;modal.showModal();onReady?.()}
function setTab(next){tab=next;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));render()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
function render(){action.classList.add('hidden');action.onclick=null;if(tab==='log'){title.textContent='Climb Tracker';renderLog()}if(tab==='projects'){title.textContent='Active Projects';renderProjects()}if(tab==='stats'){title.textContent='Climbing Stats';action.classList.remove('hidden');action.onclick=showDataMenu;renderStats()}if(tab==='body'){title.textContent='Body';action.classList.remove('hidden');action.onclick=showBodySettings;renderBody()}}
function sessionGroups(type=logType){const completed=state.climbs.filter(c=>!c.isProject&&c.type===type).sort((a,b)=>b.date-a.date),map=new Map();completed.forEach(c=>{const d=dayStart(new Date(c.date)),gym=(c.gym||'No Gym').trim()||'No Gym',k=`${d}|||${gym.toLowerCase()}`;if(!map.has(k))map.set(k,{date:d,gym,climbs:[]});map.get(k).climbs.push(c)});return [...map.values()].sort((a,b)=>b.date-a.date||a.gym.localeCompare(b.gym))}
function logSummaryBanner(){const completed=state.climbs.filter(c=>!c.isProject&&c.type===logType),hard=getHardest(completed),today=dayStart(),todayClimbs=completed.filter(c=>dayStart(new Date(c.date))===today),todayHard=getHardest(todayClimbs);return `<div class="log-summary card"><div class="log-summary-title">${logType} Summary</div><div class="log-summary-grid"><div><small>Total Climbs</small><strong>${completed.length}</strong></div><div><small>Hardest Grade</small><strong class="accent">${hard?displayGrade(hard):'—'}</strong></div></div>${todayClimbs.length?`<div class="log-today"><div class="log-today-label">Today</div><div><strong>${todayClimbs.length}</strong><small> climb${todayClimbs.length===1?'':'s'}</small></div><div><small>Hardest </small><strong class="accent">${todayHard?displayGrade(todayHard):'—'}</strong></div></div>`:''}</div>`}
function renderLog(){const groups=sessionGroups();app.innerHTML=`<div class="stack"><div class="segmented log-type-tabs"><button onclick="logType='Boulder';renderLog()" class="${logType==='Boulder'?'active':''}">Boulder</button><button onclick="logType='Sport';renderLog()" class="${logType==='Sport'?'active':''}">Sport</button></div>${logSummaryBanner()}${groups.length?groups.map(sessionCard).join(''):`<div class="empty">No ${logType.toLowerCase()} climbs yet. Tap + to log your first climb.</div>`}</div><button class="fab" onclick="showClimbForm(null,false,'${logType}')">+</button>`}
function sessionCard(session){const {date,gym,climbs:cs}=session,hard=getHardest(cs);return `<details class="card session-card"><summary class="session-summary"><div><strong>${esc(gym)}</strong><div class="muted">${ymd(date)} · ${cs.length} climb${cs.length===1?'':'s'}</div></div><div class="session-summary-right"><div><small class="muted">Hardest</small><div class="accent">${hard?displayGrade(hard):'—'}</div></div><span class="session-chevron">⌄</span></div></summary><div class="session-climbs">${cs.map(c=>climbRow(c)).join('')}</div></details>`}
function climbRow(c){return `<div class="climb-row clickable" onclick="showClimbForm(${c.id})"><div class="row"><div class="grade">${displayGrade(c)}</div><div style="flex:1"><strong>${esc(c.gym||c.type)}</strong><div class="muted">${c.incline?esc(c.incline)+' · ':''}${c.isFlash?'<span class="flash">Flash! ✨</span>':`${c.attempts} attempt${c.attempts===1?'':'s'}`}</div></div><span>›</span></div></div>`}
function gradeLabel(type,grade){return type==='Boulder'?`V${grade}`:`5.${grade}`}
function rememberedGrade(type){const key=`climbtracker.lastGrade.${type}`;const saved=localStorage.getItem(key),grades=type==='Boulder'?boulder:sport;if(saved&&grades.includes(saved))return saved;const recent=[...state.climbs].filter(c=>c.type===type).sort((a,b)=>b.date-a.date)[0];return recent&&grades.includes(recent.grade)?recent.grade:grades[0]}
function rememberGrade(type,grade){localStorage.setItem(`climbtracker.lastGrade.${type}`,grade)}
function gradeWheelMarkup(type,selected){const grades=type==='Boulder'?boulder:sport;return `<div class="grade-wheel-wrap"><div class="grade-wheel-selection" aria-hidden="true"></div><div id="gradeWheel" class="grade-wheel" role="listbox" aria-label="Grade">${grades.map(g=>`<button type="button" class="grade-wheel-item" data-grade="${g}" role="option" aria-selected="${g===selected?'true':'false'}">${gradeLabel(type,g)}</button>`).join('')}</div></div><input id="grade" type="hidden" value="${selected}">`}
function setupGradeWheel(type,selected){const wheel=document.querySelector('#gradeWheel'),input=document.querySelector('#grade');if(!wheel||!input)return;const items=[...wheel.querySelectorAll('.grade-wheel-item')],itemHeight=48;let ticking=false;function select(index,scroll=false){index=Math.max(0,Math.min(items.length-1,index));const item=items[index];input.value=item.dataset.grade;items.forEach((el,i)=>{const on=i===index;el.classList.toggle('selected',on);el.setAttribute('aria-selected',on?'true':'false')});if(scroll)wheel.scrollTo({top:index*itemHeight,behavior:'smooth'})}const initial=Math.max(0,items.findIndex(x=>x.dataset.grade===selected));requestAnimationFrame(()=>{wheel.scrollTop=initial*itemHeight;select(initial)});wheel.addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{select(Math.round(wheel.scrollTop/itemHeight));ticking=false})},{passive:true});items.forEach((item,index)=>item.onclick=()=>select(index,true))}
function showClimbForm(id=null,forceProject=false,preferredType=null){const c=id?state.climbs.find(x=>x.id===id):null;const type=c?.type||preferredType||'Boulder';const selectedGrade=c?.grade||rememberedGrade(type);openModal(c?'Edit Climb':forceProject?'Add Project':'Log Climb',`<form id="climbForm" class="form-grid"><div class="segmented"><button type="button" data-type="Boulder" class="${type==='Boulder'?'active':''}">Boulder</button><button type="button" data-type="Sport" class="${type==='Sport'?'active':''}">Sport</button></div><div><label>Grade</label><div id="gradePicker">${gradeWheelMarkup(type,selectedGrade)}</div></div><label>Gym<input id="gym" list="gyms" value="${esc(c?.gym||'')}"><datalist id="gyms">${state.gyms.map(g=>`<option value="${esc(g)}">`).join('')}</datalist></label><label>Incline<select id="incline"><option value="">None</option>${inclines.map(x=>`<option ${c?.incline===x?'selected':''}>${x}</option>`).join('')}</select></label><div><label>Hold Types</label><div id="holds" class="chips">${chipSet(holds,c?.holdTypes)}</div></div><div><label>Key Moves</label><div id="moves" class="chips">${chipSet(moves,c?.keyMoves)}</div></div><label>Attempts<input id="attempts" type="number" min="1" inputmode="numeric" value="${c?.attempts||1}"></label>${forceProject?'':`<label class="checkbox-row"><input id="project" type="checkbox" ${c?.isProject?'checked':''}> Mark as Project</label>`}<label>Description / Notes<textarea id="description">${esc(c?.description||'')}</textarea></label><div class="modal-actions">${c?'<button type="button" id="deleteClimb" class="btn danger">Delete</button>':''}<button type="button" class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn">Save</button></div></form>`,()=>{
 const form=document.querySelector('#climbForm');let currentType=type;setupGradeWheel(currentType,selectedGrade);form.querySelectorAll('[data-type]').forEach(btn=>btn.onclick=()=>{currentType=btn.dataset.type;form.querySelectorAll('[data-type]').forEach(x=>x.classList.toggle('active',x===btn));const picked=c&&c.type===currentType?c.grade:rememberedGrade(currentType);document.querySelector('#gradePicker').innerHTML=gradeWheelMarkup(currentType,picked);setupGradeWheel(currentType,picked)});form.querySelectorAll('.chip').forEach(ch=>ch.onclick=()=>ch.classList.toggle('on'));form.onsubmit=e=>{e.preventDefault();const val={id:c?.id||uid(),grade:document.querySelector('#grade').value,type:currentType,date:c?.date||Date.now(),gym:document.querySelector('#gym').value.trim()||null,incline:document.querySelector('#incline').value||null,holdTypes:selectedChips('#holds'),keyMoves:selectedChips('#moves'),description:document.querySelector('#description').value.trim()||null,attempts:Math.max(1,parseInt(document.querySelector('#attempts').value)||1),isProject:forceProject?true:document.querySelector('#project')?.checked||false};val.isFlash=val.attempts===1&&!val.isProject;rememberGrade(val.type,val.grade);if(c)state.climbs=state.climbs.map(x=>x.id===c.id?val:x);else state.climbs.push(val);if(val.gym&&!state.gyms.some(g=>g.toLowerCase()===val.gym.toLowerCase()))state.gyms.push(val.gym);closeModal();save()};if(c)document.querySelector('#deleteClimb').onclick=()=>{if(confirm('Delete this climb?')){state.climbs=state.climbs.filter(x=>x.id!==c.id);closeModal();save()}}})}
function chipSet(options,current){const cur=(current||'').split(',').map(x=>x.trim());return options.map(x=>`<button type="button" class="chip ${cur.includes(x)?'on':''}" data-value="${esc(x)}">${esc(x)}</button>`).join('')}
function selectedChips(sel){const xs=[...document.querySelector(sel).querySelectorAll('.chip.on')].map(x=>x.dataset.value);return xs.length?xs.join(','):null}
function renderProjects(){const projects=state.climbs.filter(c=>c.isProject).sort((a,b)=>b.date-a.date);const groups=Object.groupBy?Object.groupBy(projects,c=>c.gym||'No Gym'):projects.reduce((m,c)=>((m[c.gym||'No Gym']??=[]).push(c),m),{});app.innerHTML=`<div class="stack">${projects.length?Object.entries(groups).map(([gym,items])=>`<div><div class="section-title">${esc(gym)}</div>${items.map(projectCard).join('')}</div>`).join(''):`<div class="empty">No active projects.</div>`}</div><button class="fab" onclick="showClimbForm(null,true)">+</button>`}
function projectCard(c){return `<div class="card project-card"><div class="row between"><div><div class="grade">${displayGrade(c)}</div><div class="muted">${esc(c.incline||c.type)}</div></div><strong>${c.attempts} attempts</strong></div>${c.description?`<div>${esc(c.description)}</div>`:''}<div class="toolbar"><button class="btn secondary" onclick="projectAttempt(${c.id})">+1 Attempt</button><button class="btn" onclick="sendProject(${c.id})">Sent ✓</button><button class="btn secondary" onclick="showClimbForm(${c.id})">Edit</button></div></div>`}
function projectAttempt(id){const c=state.climbs.find(x=>x.id===id);c.attempts++;save()}
function sendProject(id){const c=state.climbs.find(x=>x.id===id);c.attempts++;c.isProject=false;c.isFlash=false;c.date=Date.now();save()}
function filteredStats(){return state.climbs.filter(c=>!c.isProject&&c.type===statsType&&(!statsGrade||c.grade===statsGrade))}
function renderStats(){const all=state.climbs.filter(c=>!c.isProject&&c.type===statsType),grades=[...new Set(all.map(c=>c.grade))].sort((a,b)=>gradeScore(a)-gradeScore(b)),cs=filteredStats(),sessions=new Set(cs.map(c=>dayStart(new Date(c.date)))),hard=getHardest(cs),flashes=Object.entries(cs.filter(c=>c.isFlash).reduce((m,c)=>((m[c.grade]=(m[c.grade]||0)+1),m),{})).filter(([,n])=>n>=5).map(([g])=>g).sort((a,b)=>gradeScore(b)-gradeScore(a))[0];const counts=cs.reduce((m,c)=>((m[c.grade]=(m[c.grade]||0)+1),m),{}),max=Math.max(1,...Object.values(counts));app.innerHTML=`<div class="stack"><div class="segmented"><button onclick="statsType='Boulder';statsGrade=null;renderStats()" class="${statsType==='Boulder'?'active':''}">Boulder</button><button onclick="statsType='Sport';statsGrade=null;renderStats()" class="${statsType==='Sport'?'active':''}">Sport</button></div>${grades.length?`<div class="chips"><button class="chip ${statsGrade===null?'on':''}" onclick="statsGrade=null;renderStats()">All</button>${grades.map(g=>`<button class="chip ${statsGrade===g?'on':''}" onclick="statsGrade='${g}';renderStats()">${statsType==='Boulder'?'V':'5.'}${g}</button>`).join('')}</div>`:''}<div class="metric-grid"><div class="metric"><small>Total</small><strong>${cs.length}</strong></div><div class="metric"><small>Avg. Climbs / Session</small><strong>${sessions.size?(cs.length/sessions.size).toFixed(1):'—'}</strong></div><div class="metric"><small>Hardest</small><strong>${hard?displayGrade(hard):'—'}</strong></div><div class="metric"><small>Flash Grade</small><strong>${flashes?(statsType==='Boulder'?'V':'5.')+flashes:'—'}</strong></div><div class="metric"><small>Avg. Attempts</small><strong>${cs.length?(cs.reduce((n,c)=>n+c.attempts,0)/cs.length).toFixed(1):'—'}</strong></div><div class="metric"><small>Flash Rate</small><strong>${cs.length?Math.round(cs.filter(c=>c.isFlash).length/cs.length*100)+'%':'—'}</strong></div></div><div class="card"><h3>Grade Distribution</h3><div class="bar-wrap" style="margin-top:14px">${Object.keys(counts).sort((a,b)=>gradeScore(a)-gradeScore(b)).map(g=>`<div class="bar-row"><span>${statsType==='Boulder'?'V':'5.'}${g}</span><div class="bar"><i style="width:${counts[g]/max*100}%"></i></div><b>${counts[g]}</b></div>`).join('')||'<div class="empty">No data</div>'}</div></div></div>`}
function todayLog(){return state.logs.find(l=>l.date===dayStart())}
function upsertLog(date,patch){let l=state.logs.find(x=>x.date===date);if(!l){l={id:uid(),date,calories:null,weight:null,calorieHistory:null};state.logs.push(l)}Object.assign(l,patch)}
function renderBody(){const t=todayLog(),hist=(t?.calorieHistory||'').split(',').filter(Boolean),past=[...state.logs].filter(l=>l.date<dayStart()).sort((a,b)=>b.date-a.date),weights=past.map(l=>l.weight).filter(x=>x!=null).slice(0,7),cals=past.map(l=>l.calories).filter(x=>x!=null).slice(0,7),aw=weights.length?weights.reduce((a,b)=>a+b,0)/weights.length:null,ac=cals.length?cals.reduce((a,b)=>a+b,0)/cals.length:null,goal=state.calorieGoal||0;app.innerHTML=`<div class="stack"><div class="card"><div class="row between"><h3 class="accent">Today's Total: ${t?.calories||0} Cals</h3>${goal?`<span class="muted">Goal ${goal}</span>`:''}</div>${goal?`<div class="progress" style="margin-top:10px"><i style="width:${Math.min(100,(t?.calories||0)/goal*100)}%"></i></div>`:''}<div class="row" style="margin-top:14px"><input id="calInput" type="number" min="0" inputmode="numeric" placeholder="Add Calories"><button class="btn" onclick="addCalories()">Add</button></div>${hist.length?`<div style="margin-top:12px">${hist.map((x,i)=>`<div class="cal-history row between"><span>Entry ${i+1}: ${x} Calories</span><button class="btn secondary" onclick="deleteCal(${i})">Delete</button></div>`).join('')}</div>`:''}</div><div class="card">${t?.weight!=null?`<div class="row between"><div><small class="muted">Today's Weight</small><div class="big">${t.weight} lbs</div></div><button class="btn secondary" onclick="showWeightForm()">Edit</button></div>`:`<div class="row"><input id="weightInput" type="number" step="0.1" inputmode="decimal" placeholder="Today's Weight (lbs)"><button class="btn" onclick="saveWeight()">Save</button></div>`}</div><div class="metric-grid"><div class="metric"><small>7-Day Avg Weight</small><strong>${aw!=null?aw.toFixed(1)+' lbs':'—'}</strong></div><div class="metric"><small>7-Day Avg Cals</small><strong>${ac!=null?Math.round(ac):'—'}</strong></div></div><div class="card"><h3>Recent Logs</h3>${state.logs.length?[...state.logs].sort((a,b)=>b.date-a.date).slice(0,10).map(l=>`<div class="climb-row row between"><span>${ymd(l.date)}</span><span class="muted">${l.calories??'—'} cal · ${l.weight??'—'} lb</span></div>`).join(''):'<div class="empty">No logs yet.</div>'}</div></div>`}
function addCalories(){const n=parseInt(document.querySelector('#calInput').value);if(!Number.isFinite(n))return;const d=dayStart(),l=todayLog(),arr=(l?.calorieHistory||'').split(',').filter(Boolean);arr.push(String(n));upsertLog(d,{calories:(l?.calories||0)+n,calorieHistory:arr.join(',')});save()}
function deleteCal(i){const l=todayLog();if(!l)return;const arr=(l.calorieHistory||'').split(',').filter(Boolean),n=parseInt(arr[i])||0;arr.splice(i,1);l.calories=Math.max(0,(l.calories||0)-n);l.calorieHistory=arr.length?arr.join(','):null;save()}
function saveWeight(){const n=parseFloat(document.querySelector('#weightInput').value);if(!Number.isFinite(n))return;upsertLog(dayStart(),{weight:n});save()}
function showWeightForm(){const l=todayLog();openModal('Update Weight',`<form id="weightForm" class="form-grid"><label>Weight (lbs)<input id="modalWeight" type="number" step="0.1" value="${l?.weight||''}"></label><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn">Save</button></div></form>`,()=>document.querySelector('#weightForm').onsubmit=e=>{e.preventDefault();const n=parseFloat(document.querySelector('#modalWeight').value);if(Number.isFinite(n)){upsertLog(dayStart(),{weight:n});closeModal();save()}})}
function showBodySettings(){openModal('Body Settings',`<form id="bodySettings" class="form-grid"><label>Daily Calorie Goal<input id="goal" type="number" min="0" value="${state.calorieGoal||''}"></label><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn">Save</button></div></form>`,()=>document.querySelector('#bodySettings').onsubmit=e=>{e.preventDefault();state.calorieGoal=parseInt(document.querySelector('#goal').value)||0;closeModal();save()})}
function showDataMenu(){const last=localStorage.getItem('climbtracker.drive.lastBackup');openModal('Data',`<div class="stack"><button class="btn" onclick="backupToGoogleDrive()">Back Up to Google Drive</button><button class="btn secondary" onclick="restoreFromGoogleDrive()">Restore From Google Drive</button>${last?`<div class="muted">Last Drive backup: ${esc(new Date(last).toLocaleString())}</div>`:''}<button class="btn secondary" onclick="exportCsv()">Download CSV Backup</button><button class="btn secondary" onclick="document.querySelector('#csvInput').click();closeModal()">Import CSV Backup</button></div>`) }
function csvEscape(v){v=v==null?'':String(v);return /[,"\n]/.test(v)?`"${v.replaceAll('"','""')}"`:v}
function formatCsvDate(ts){const d=new Date(ts),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`}
function buildCsv(){let s='[CLIMBS]\ngrade,type,date,gym,incline,holdTypes,keyMoves,description,attempts,isFlash,isProject\n';state.climbs.forEach(c=>s+=[c.grade,c.type,formatCsvDate(c.date),c.gym,c.incline,c.holdTypes,c.keyMoves,c.description,c.attempts,c.isFlash,c.isProject].map(csvEscape).join(',')+'\n');if(state.logs.length){s+='\n[LOGS]\ndate,calories,weight,calorieHistory\n';state.logs.forEach(l=>s+=[formatCsvDate(l.date),l.calories,l.weight,l.calorieHistory].map(csvEscape).join(',')+'\n')}return s}
function exportCsv(){const blob=new Blob([buildCsv()],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='climbing_data.csv';a.click();URL.revokeObjectURL(a.href);closeModal()}
function loadGoogleIdentity(){return new Promise((resolve,reject)=>{if(window.google?.accounts?.oauth2)return resolve();const existing=document.querySelector('script[data-google-identity]');if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',()=>reject(new Error('Could not load Google sign-in.')),{once:true});return}const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.defer=true;script.dataset.googleIdentity='true';script.onload=resolve;script.onerror=()=>reject(new Error('Could not load Google sign-in.'));document.head.appendChild(script)})}
async function backupToGoogleDrive(){if(GOOGLE_CLIENT_ID.startsWith('PASTE_')){alert('Google Drive backup is not configured yet. Add your Google OAuth Client ID to app.js first.');return}try{await loadGoogleIdentity()}catch(e){alert(e.message);return}if(!googleTokenClient){googleTokenClient=google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CLIENT_ID,scope:DRIVE_SCOPE,callback:async response=>{if(response.error){alert(`Google authorization failed: ${response.error}`);return}try{await uploadDriveBackup(response.access_token)}catch(e){console.error(e);alert(`Drive backup failed: ${e.message}`)}}})}googleTokenClient.requestAccessToken({prompt:''})}
async function driveFetch(url,token,options={}){const headers=new Headers(options.headers||{});headers.set('Authorization',`Bearer ${token}`);const response=await fetch(url,{...options,headers});if(!response.ok){let detail='';try{detail=(await response.json()).error?.message||''}catch{}throw new Error(detail||`Google Drive returned ${response.status}`)}return response}
async function findDriveBackup(token){const q=encodeURIComponent(`name='${DRIVE_BACKUP_NAME.replaceAll("'","\\'")}' and trashed=false`);const fields=encodeURIComponent('files(id,name,modifiedTime)');const response=await driveFetch(`https://www.googleapis.com/drive/v3/files?q=${q}&spaces=drive&orderBy=modifiedTime%20desc&pageSize=10&fields=${fields}`,token);const data=await response.json();return data.files?.[0]||null}
async function uploadDriveBackup(token){const csv=buildCsv();let file=await findDriveBackup(token);if(file){const response=await driveFetch(`https://www.googleapis.com/upload/drive/v3/files/${encodeURIComponent(file.id)}?uploadType=media&fields=id,name,modifiedTime`,token,{method:'PATCH',headers:{'Content-Type':'text/csv;charset=utf-8'},body:csv});file=await response.json()}else{const boundary='climbtracker_'+Math.random().toString(36).slice(2);const metadata=JSON.stringify({name:DRIVE_BACKUP_NAME,mimeType:'text/csv'});const body=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${metadata}\r\n--${boundary}\r\nContent-Type: text/csv; charset=UTF-8\r\n\r\n${csv}\r\n--${boundary}--`;const response=await driveFetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,modifiedTime',token,{method:'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body});file=await response.json()}localStorage.setItem('climbtracker.drive.lastBackup',new Date().toISOString());closeModal();alert(`Backup complete: ${file.name||DRIVE_BACKUP_NAME}`)}
async function restoreFromGoogleDrive(){if(GOOGLE_CLIENT_ID.startsWith('PASTE_')){alert('Google Drive backup is not configured yet. Add your Google OAuth Client ID to app.js first.');return}try{await loadGoogleIdentity()}catch(e){alert(e.message);return}if(!googleRestoreTokenClient){googleRestoreTokenClient=google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CLIENT_ID,scope:DRIVE_SCOPE,callback:async response=>{if(response.error){alert(`Google authorization failed: ${response.error}`);return}try{await downloadDriveBackup(response.access_token)}catch(e){console.error(e);alert(`Drive restore failed: ${e.message}`)}}})}googleRestoreTokenClient.requestAccessToken({prompt:''})}
async function downloadDriveBackup(token){const file=await findDriveBackup(token);if(!file){alert(`${DRIVE_BACKUP_NAME} was not found in Google Drive.`);return}const response=await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}?alt=media`,token);const text=await response.text();const parsed=parseBackupCsv(text);if(!parsed.climbs.length&&!parsed.logs.length){throw new Error('The Drive backup does not contain any valid Climb Tracker data.')}const ok=confirm(`Restore ${parsed.climbs.length} climbs and ${parsed.logs.length} daily logs from Google Drive?\n\nThis will replace the climbs and daily logs currently stored on this device.`);if(!ok)return;applyParsedBackup(parsed,true);closeModal();save();alert(`Restore complete: ${parsed.climbs.length} climbs and ${parsed.logs.length} daily logs.`)}
function parseLine(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===','&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return out}
function parseDate(s){const m=s.match(/^(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2}):(\d{2})$/);if(m)return new Date(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+m[6]).getTime();const n=Number(s);return Number.isFinite(n)?n:Date.parse(s)}
function parseBackupCsv(text){const lines=text.split(/\r?\n/);let sec='';const climbs=[],logs=[];for(const raw of lines){const line=raw.trimEnd();if(!line)continue;if(line==='[CLIMBS]'){sec='c';continue}if(line==='[LOGS]'){sec='l';continue}if(line.startsWith('grade,type')||line.startsWith('date,calories'))continue;if(!sec&&line.includes(','))sec='c';const p=parseLine(line);if(sec==='c'&&p.length>=11){const date=parseDate(p[2]);if(!Number.isFinite(date))continue;climbs.push({id:uid()+climbs.length,grade:p[0],type:p[1],date,gym:p[3]||null,incline:p[4]||null,holdTypes:p[5]||null,keyMoves:p[6]||null,description:p[7]||null,attempts:parseInt(p[8])||1,isFlash:p[9].trim().toLowerCase()==='true',isProject:p[10].trim().toLowerCase()==='true'})}else if(sec==='l'&&p.length>=3){const date=parseDate(p[0]);if(!Number.isFinite(date))continue;logs.push({id:uid()+logs.length,date,calories:p[1]?parseInt(p[1]):null,weight:p[2]?parseFloat(p[2]):null,calorieHistory:p[3]||null})}}return {climbs,logs}}
function applyParsedBackup(parsed,replace=false){if(replace){state.climbs=parsed.climbs;state.logs=parsed.logs;state.gyms=[]}else{state.climbs.push(...parsed.climbs);state.logs.push(...parsed.logs)}for(const c of state.climbs)if(c.gym&&!state.gyms.some(g=>g.toLowerCase()===c.gym.toLowerCase()))state.gyms.push(c.gym)}
csvInput.onchange=async()=>{const f=csvInput.files[0];if(!f)return;const parsed=parseBackupCsv(await f.text());applyParsedBackup(parsed,false);csvInput.value='';save();alert(`Imported ${parsed.climbs.length} climbs and ${parsed.logs.length} daily logs.`)};
if('serviceWorker' in navigator)window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await reg.update()}catch(e){console.warn('Service worker update failed',e)}});
render();
